// lang.js - 언어 텍스트 중앙 관리
const Lang = (() => {

  let current = 'ko'; // 기본값

  const TEXT = {
    ko: {
      // ── 언어 선택 ──
      langSelect: {
        title: '언어를 선택하세요',
        ko: '한국어',
        en: 'English',
      },

      // ── 인트로 슬라이드 ──
      intro: [
        { lines: ['먼 옛날,', '인간과 귀신이 함께 살던 나라가 있었다.'] },
        { lines: ['귀-인-국 (鬼人國)', '신령이 균형을 잡고,', '귀인이 인간과 함께 살아가던 세상.'], accent: true },
        { lines: ['그러나...', '하늘 밖에서 정체불명의 존재가 왔다.'] },
        { lines: ['기어오는 혼돈.', '세상의 법칙을 뒤틀어버리는 외신.', '귀-인-국은 무너졌다.'], shake: true },
        // [UPDATE 2026-07-15] 260715_MTOPC.md 6번: 삼신할매 태몽 한 줄 추가 (스포일러 없이 은유)
        { lines: ['모든 것이 폐허가 된 지금,', '삼신할머니가 마지막 무당을 깨웠다.', '— 하나였던 달이 둘로 갈라지더니, 다시 하나로 겹쳐지는 꿈이었다.'] },
        { lines: ['"애기씨,"', '"흩어진 귀-인을 모아라."', '"멸망한 나라를 되살려라."'], accent: true },
        { lines: ['기어오는 혼돈을 봉인하고,', '귀-인-국을 다시 세울 자.', '그것이 당신이다.'] },
      ],

      // ── 공통 UI ──
      ui: {
        skip:        'SKIP',
        tapToStart:  '✦ 터치하여 시작 ✦',
        settings:    '설정',
        language:    '언어',
        back:        '뒤로',
        confirm:     '확인',
        cancel:      '취소',
        gold:        '골드',
        gem:         '보석',
      },

      // ── 네비 ──
      nav: {
        stage:       '스테이지',
        daejanggan:  '대장간',
        companion:   '의원당',
        weapon:      '서낭당',
        building:    '장승당',
        pet:         '펫',
        petTooltip:  '용왕연못',
        player:      '캐릭터',
        sinmok:      '신목',
      },
      onboarding: { // [UPDATE 2026-07-09] 초반 온보딩 유도 문구
        tapStage: '여기를 눌러봐!',
        tapStage1: '스테이지 1을 눌러봐!',
        zoomHint: '두 손가락으로도 확대/축소할 수 있어요', // [UPDATE 2026-07-13] 260713_MTOPC.md 20번
        atkUpgradeHint: '공격력 강화가 가능해요!', // [UPDATE 2026-07-15] 스테이지1 클리어 직후 온보딩
      },
      currency: {
        gold:           '골드',
        gems:           '다이아',
        ganghwaseok:    '강화석',
        cheonunseok:    '천운석',
        cheonryeonggwa: '천령과',
        taegeukseok:    '태극석',
        chaewonseok:    '차원석',
        hondonseok:     '혼돈석', // [UPDATE 2026-07-15] 260715_MTOPC.md 4/9번
        sullriseok:     '순리석',
      },
      dungeon: {
        ganghwaseok:    '강화석 던전',
        infinite:       '무한 던전',
        bossrush:       '보스러쉬',
        cheonunseok:    '천운석 던전',
        cheonryeonggwa: '천령과 던전',
        taegeukseok:    '태극석 던전',
        hondonseok:     '혼돈석 던전', // [UPDATE 2026-07-15] 260715_MTOPC.md 4/9번
        sullriseok:     '순리석 던전',
        title:          '던전',
        infiniteTitle:  '무한 모드',
        infiniteDesc:   '끝없는 파도를 버텨라',
        infiniteDetail: '⏱️ 시간 무제한 · 🪙 골드 드롭 2배',
        infiniteDetail2:'파도가 지날수록 적이 강해진다. 얼마나 버틸 수 있을까?',
        bestRecord:     '최고 기록',
        noRecord:       '없음',
        enter:          '입장 →',
        bossRushTitle:  '보스 러쉬',
        bossRushDesc:   '역대 보스들과 연속 격돌',
        bossRushDetail: '💎 보스 처치마다 다이아 획득',
        bossRushDetail2:'10명의 보스가 기다린다. 쓰러지면 그게 끝.',
        bossRecord:     '보스',
        totalGem:       '총 획득',
        hint:           '던전은 스테이지 클리어와 별개로 언제든 도전 가능',
        back:           '← 귀환',
        minSec:         '분',
        sec:            '초',
        recordTimeTpl:  '{m} 분 {s}초', // [UPDATE 2026-08-06] 기록 시간 표시(예: "3 분 20초")
        // [UPDATE 2026-08-06] 텍스트 중앙화 (dungeon-scene.js)
        noRecordText:        '기록 없음',
        bestLabel:           '최고:',
        enterPlain:          '입장',
        noDungeonsUnlocked:  '스테이지 5 클리어 시\n강화석 던전이 해금됩니다.',
        upgradeTitle:        '던전강화',
        power:               '전투력',
        ratingSafe:          '적정',
        ratingRisky:         '위험',
        ratingDanger:        '매우위험',
        startFromKillTpl:    '무한던전 진입 시 {n}킬 지점부터 시작합니다 (몬스터 배율도 그 기준).',
        downgradeRefundTpl:  '레벨 다운 시 {gold}골드 + {stone}천운석 환급',
        desc_ganghwaseok:    '골드 대신 강화석이 드랍됩니다.',
        desc_infinite:       '골드 파밍용 무한 모드 던전.',
        desc_bossrush:       '보스 10마리 연속 도전, 다이아 획득.',
        desc_cheonunseok:    '골드 대신 천운석이 드랍됩니다.',
        desc_cheonryeonggwa: '골드 대신 천령과가 드랍됩니다.',
        desc_taegeukseok:    '골드 대신 태극석이 드랍됩니다.',
        desc_hondonseok:     '골드 대신 혼돈석이 드랍됩니다.',
        desc_sullriseok:     '골드 대신 순리석이 드랍됩니다.',
      },

      // ── 로비 ──
      lobby: {
        enterBuilding:     '▲ 진입',
        locked:            '🔒',
        slotUnlockedTitle: '슬롯 해금!',
        slotExpandedMsg:   '{n}개로 늘어났어요!',
        slotExpandedBody:  '주무기 · 동료 · 펫 슬롯이',
        slotConfirm:       '확인!',
        diffEasy:          '이지',
        diffNormal:        '노말',
        diffHard:          '하드',
      },

      // ── 업적 ──
      achievement: {
        title:          '🏆 업적',
        onceSect:       '◆ 일회성 업적',
        infiniteSect:   '◆ 무한 반복 업적',
        claim:          '수령',
        claimed:        '수령완료',
        claimAll:       '일괄수령',
        current:        '현재',
        tier:           '단계',
        first_win_name:         '첫 승리',
        first_win_desc:         '처음으로 스테이지를 클리어했다',
        first_lose_name:        '첫 패배',
        first_lose_desc:        '처음으로 쓰러졌다',
        first_boss_name:        '첫 보스 처치',
        first_boss_desc:        '처음으로 보스를 물리쳤다',
        first_companion_name:   '첫 동료',
        first_companion_desc:   '처음으로 동료를 편성했다',
        first_pet_name:         '첫 펫',
        first_pet_desc:         '처음으로 펫을 획득했다',
        first_building_name:    '첫 건물 강화',
        first_building_desc:    '처음으로 건물을 강화했다',
        first_evolve_name:      '첫 각성',
        first_evolve_desc:      '처음으로 무기를 각성시켰다',
        all_chapters_name:      '전 챕터 정복',
        all_chapters_desc:      '모든 챕터를 클리어했다',
        total_kills_name:       '총 처치 수',
        total_wins_name:        '총 클리어 수',
        total_runs_name:        '총 출격 수',
        total_kills_inf_name:   '끝없는 사냥',
        boss_chapters_inf_name: '보스 사냥꾼',
        total_wins_inf_name:    '연이은 승전',
        total_runs_inf_name:    '멈추지 않는 출격',
        season1_full_name:      '현계 완주',
        season1_full_desc:      '시즌1(현계)을 클리어했다',
        season2_full_name:      '유명계 완주',
        season2_full_desc:      '시즌2(유명계)를 클리어했다',
        season3_full_name:      '망랑계 완주',
        season3_full_desc:      '시즌3(망랑계)을 클리어했다',
        season4_full_name:      '귀허계 완주',
        season4_full_desc:      '시즌4(귀허계)를 클리어했다',
        season5_full_name:      '선계 완주',
        season5_full_desc:      '시즌5(선계)를 클리어했다',
        hard_clear_name:        '첫 하드 클리어',
        hard_clear_desc:        '하드 난이도로 스테이지를 처음 클리어했다',
        companion_5_name:       '동료 수집가 I',
        companion_5_desc:       '동료를 5명 보유했다',
        companion_10_name:      '동료 수집가 II',
        companion_10_desc:      '동료를 10명 보유했다',
        companion_15_name:      '동료 수집가 III',
        companion_15_desc:      '동료를 15명 보유했다',
        pet_5_name:              '펫 수집가 I',
        pet_5_desc:              '펫을 5마리 보유했다',
        pet_10_name:             '펫 수집가 II',
        pet_10_desc:             '펫을 10마리 보유했다',
        pet_15_name:             '펫 수집가 III',
        pet_15_desc:             '펫을 15마리 보유했다',
        companion_4star_name:    '별이 빛나는 동료',
        companion_4star_desc:    '동료 한 명을 4성까지 강화했다',
        companion_awakened_name: '동료 각성',
        companion_awakened_desc: '동료 한 명을 각성시켰다',
        seonsul_unlock_name:     '선술 입문',
        seonsul_unlock_desc:     '선술 스킬트리를 처음 배웠다',
        seonsul_dual_tree_name:  '음양 조화',
        seonsul_dual_tree_desc:  '선술 두 번째 나무를 개화했다',
        building_lv5_name:       '번영하는 마을',
        building_lv5_desc:       '건물 하나를 5단계까지 강화했다',
        gold_10k_name:           '재물 축적',
        gold_10k_desc:           '골드 10,000을 보유했다',
        gem_50_name:             '보석함',
        gem_50_desc:             '보석 50개를 보유했다',
        kills_50000_name:        '학살자',
        kills_50000_desc:        '누적 처치 수 50,000을 달성했다',
      },

      // ── 스테이지 ──
      chapters: [
        '잊혀진 무덤',
        '안개의 폐촌',
        '타락한 서낭당',
        '신령의 숲',
        '혼돈의 균열',
        '저승의 문턱',
        '공허의 탑',
        '망각의 바다',
        '외신의 영역',
        '귀인국의 심장',
      ],

      // ── 설정 메뉴 ──
      settingsMenu: {
        title:    '설정',
        language: '언어 설정',
        sound:    '효과음',
        bgm:      '배경음악',
        version:  '버전',
        tutorial: '도움말',
        redeemCode: '코드 입력', // [UPDATE 2026-07-15] 260715_MTOPC.md 2번
        redeemCodePlaceholder: '코드를 입력하세요',
        redeemCodeSubmit: '확인',
        // [UPDATE 2026-07-17] 세이브 코드 (PC↔모바일 이동용, itch.io는 자동 동기화 안 됨)
        saveCode: '💾 세이브 코드',
        saveCodeExport: '내보내기',
        saveCodeImport: '불러오기',
        saveCodeExportTitle: '세이브 코드 내보내기',
        saveCodeExportDesc: '아래 코드를 복사해서 안전한 곳에 보관하세요. 다른 기기의 "불러오기"에 붙여넣으면 진행 상황을 그대로 옮길 수 있습니다.',
        saveCodeCopyBtn: '📋 복사하기',
        saveCodeCopied: '복사되었습니다!',
        saveCodeCopyManual: '복사 버튼이 지원되지 않는 환경입니다. 아래 코드를 길게 눌러 직접 선택/복사해주세요.',
        saveCodeImportTitle: '세이브 코드 불러오기',
        saveCodeImportPlaceholder: '세이브 코드를 붙여넣으세요',
        saveCodeImportSubmit: '확인',
        saveCodeInvalid: '유효하지 않은 코드입니다.',
        saveCodeChecksumError: '코드가 손상되었거나 일부가 잘렸습니다. 전체를 정확히 복사했는지 확인해주세요.',
        saveCodePreviewTitle: '이 세이브를 적용할까요?',
        saveCodePreviewVersion: '버전',
        saveCodePreviewStage: '최고 스테이지',
        saveCodePreviewAchievements: '업적',
        saveCodePreviewBuildings: '건물',
        saveCodePreviewCompanions: '동료',
        saveCodePreviewPets: '펫',
        saveCodePreviewCurrency: '재화',
        saveCodePreviewSavedAt: '저장 시각',
        saveCodePreviewDevice: '저장 기기',
        saveCodeApply: '적용하기',
        // [UPDATE 2026-07-31] 자동 백업이 생기면서 "되돌릴 수 없습니다"가 더 이상 사실이 아니게 됨 — 문구 교체
        saveCodeApplyWarn: '⚠️ 현재 진행 상황을 덮어씁니다.\n덮어쓰기 전 자동 백업되며, 설정에서 1회 복구할 수 있습니다.',
        saveCodeCancel: '취소',
        saveCodeApplied: '적용되었습니다. 잠시 후 로비로 돌아갑니다...',
        // [UPDATE 2026-07-31] 세이브 코드 복구 — 불러오기로 덮어쓰기 직전에 자동 보관된 백업으로 되돌리기
        saveCodeRestore: '↩️ 복구',
        saveCodeRestoreTitle: '직전 세이브로 복구',
        saveCodeRestoreDesc: '세이브 코드를 불러오기 직전에 자동 보관된 세이브로 되돌립니다.',
        saveCodeRestoreWarn: '⚠️ 지금의 진행 상황은 사라집니다.\n백업은 1회용이라 복구 후에는 다시 되돌릴 수 없습니다.',
        saveCodeRestoreConfirm: '복구하기',
        saveCodeRestoreDone: '복구되었습니다. 잠시 후 로비로 돌아갑니다...',
        saveCodeRestoreFail: '복구할 백업이 없습니다.',
        devicePC: 'PC',
        deviceMobile: '모바일',
        // [UPDATE 2026-07-16] 설정 - 초기화(리부트) 버튼
        reboot: '🔄 리부트',
        rebootWarn1: '경고: 어떠한 보상도 없습니다. 처음부터 다시 게임을 하기 위한 버튼일 뿐입니다.\n계속 하시겠습니까?',
        rebootWarn2: '경고: 진짜 아무런 보상 없이 처음부터 다시 시작됩니다. 히든 요소도 없습니다.',
        rebootWarn3: '경고: 마지막 경고입니다. 처음부터 게임을 하는 용도 외 어떠한 용도도 없습니다.',
        rebootYes: '예',
        rebootNo: '아니오',
        rebootDone: '게임이 처음부터 다시 시작됩니다.',
        rebootBonus: '🎉 히든 업적 달성: 초기화의 결단 — 다이아 +5000! (1회성)',
        rebootConfirmClose: '확인',
      },

      // ── 튜토리얼 ──
      tutorial: {
        title:   '몽달퇴마록 입문',
        skip:    '건너뛰기',
        prev:    '이전',
        next:    '다음',
        close:   '시작하기!',
        slide1_title: '🎮 이동과 전투',
        slide1_body:  '모바일: 화면 왼쪽 조이스틱으로 이동\nPC: 방향키 또는 WASD\n\n애기씨는 가장 가까운 적을 자동으로 공격합니다.\n살아남아 귀신들을 모두 퇴마하세요!',
        slide2_title: '⚔️ 무기 & 레벨업',
        slide2_body:  '적을 처치하면 경험치를 얻습니다.\n레벨업 시 무기를 선택하거나 강화할 수 있어요.\n\n무기를 3번 강화하면 더욱 강력한 형태로 진화합니다!',
        slide3_title: '👥 동료 & 펫',
        slide3_body:  '로비에서 동료와 펫을 편성할 수 있어요.\n\n동료: 함께 싸우며 공격, 방어, 회복 등 역할 담당\n펫: 수동적 능력치 강화 또는 특수 능력 발동',
        slide4_title: '🏛️ 건물 업그레이드',
        slide4_body:  '로비의 건물을 클릭하면 골드로 업그레이드할 수 있어요.\n\n업그레이드하면 체력, 공격력, 골드 획득 등\n영구적으로 능력치가 강화됩니다!',
      },

      // ── 동료 화면 ──
      character: {
        title:       '동료',
        formation:   '편성',
        emptySlot:   '빈 슬롯',
        owned:       '보유 동료',
        active:      '편성됨',
        back:        '← 귀환',
        deploy:           '편성',
        shopBtn:          '🎪 동료 상점 (뽑기) →',
        elementRelations: '오행 상생상극 (색상 = 편성 중)', // [UPDATE 2026-08-06] 텍스트 중앙화
        nextAwakening:    '다음',
        fragCount:        '파편',
        canSummon:        '소환 가능!',
        summonBtn:        '🎴 파편 10개로 소환',
        uniFragBtn:       '✨ 만능파편 5개 → 별 추가',
        awoken:           '각성',
        slotUnlockNormal: '노말 해금',
        slotUnlockHard:   '하드 해금',
        rarity_common:    '커먼',
        rarity_uncommon:  '언커먼',
        rarity_rare:      '레어',
        rarity_unique:    '유니크',
        rarity_epic:      '에픽',
        rarity_legendary: '레전더리',
        rarity_mythos:    '미소스',
        rarity_special:   '★스페셜',
        rarity_universal: '만능', // [UPDATE 2026-08-06] 텍스트 중앙화(shop-scene.js) — 만능 파편 등급
        role_tank:      '탱커',
        role_dps:       '딜러',
        role_healer:    '힐러',
        role_support:   '서포터',
        role_assassin:  '암살자',
      },

      // ── 캐릭터(플레이어) 화면 ──
      player: {
        title:         '캐릭터',
        charName:      '애기씨',
        charSubtitle:  '마지막 무당',
        upgradeHint:   '로비에서 골드로 영구 강화 가능',
        mainWeapon:    '주무기',
        weaponLocked:  '🔒 스테이지 10 클리어 시 주무기를 변경할 수 있습니다.',
        equipped:      '장착중',
        statSection:   '스탯 & 강화',
        upgradeBtn:    '강화',
        upgraded:      '강화됨',
        upgradeHintFooter: '인게임 레벨업 시 스탯 자동 상승 · 런 종료 후 초기화',
        upgradeFooter2:    '골드 강화는 영구 적용',
        back:          '← 귀환',
        slotLabel:     '주무기 슬롯',
        slotDeselect:  '(클릭해서 해제)',
        stat_atk: { label:'공격력',   desc:'무기 피해량 증가' },
        stat_spd: { label:'공격속도', desc:'무기 쿨타임 단축' },
        stat_mov: { label:'이동속도', desc:'플레이어 이동 속도' },
        stat_def: { label:'방어력',   desc:'받는 피해 감소' },
        stat_eva: { label:'회피율',   desc:'피해 회피 확률 (최대 40%)' },
        stat_hp:  { label:'체력',     desc:'최대 체력 증가' }, // [UPDATE 2026-07-16] 260716_MTOPC.md 3번: 백엔드는 이미 있었는데 UI 노출이 빠져있던 항목
      },

      // ── 신목 강화 ──
      sinmok: {
        title:           '🌳 신목 영구강화',
        locked:          '(스테이지 30 클리어 해금)',
        current:         '현재',
        stat_critChance: '치명타 확률',
        stat_critMult:   '치명타 배율',
        stat_atkSpd:     '공격속도',
        stat_movSpd:     '이동속도',
        stat_evasion:    '회피율',
      },

      // ── 펫 화면 ──
      pet: {
        title:       '펫',
        formation:   '편성',
        emptySlot:   '빈 슬롯',
        activeEffect:'현재 적용 효과',
        owned:       '보유 펫',
        active:      '편성됨',
        back:        '← 귀환',
        // [UPDATE 2026-08-06] 텍스트 중앙화
        maxLabel:    'MAX',
        lvLabel:     '{n}강',
        unlock:      '해금',
        deploy:      '편성',
        upgrade:     '강화',
        clearChapterToUnlock: '챕터{n} 클리어 시 해금',
        unlockSeasonRequired: '시즌{n} 해금 필요',
      },

      // [UPDATE 2026-07-19] 보물 창고(Vault) — 각 계의 특산품(하드모드 전용 드랍) 보관소
      vault: {
        title:       '보물 창고',
        tabSpecialty:'특산품',
        tabLaw:      '법칙-유물',
        lawLocked:   '아직 열리지 않은 칸이다.',
        hardOnly:    '하드 난이도 스테이지 전용 드랍',
        owned:       '보유',
        back:        '← 귀환',
        // [UPDATE 2026-08-06] 텍스트 중앙화
        kindPlain:       '일반',
        kindConditional: '조건형',
        subTabPassive:   '패시브 (슬롯 불필요, 보유만 해도 적용)',
        subTabActive:    '액티브 (3슬롯 장착)',
        emptySlot:       '빈 슬롯',
        passive:         '패시브',
        active:          '액티브',
        appliedBadge:    '✓ 적용 중',
        maxLabel:        '만렙',
        locked:          '미해금',
        unlock:          '해금',
        enhance:         '강화',
        equip:           '장착',
        equippedBadge:   '✓ 장착 중',
        have:            '보유 {icon}{n}',
      },

      // ── 상점(shop-scene.js) ── [UPDATE 2026-08-06] 텍스트 중앙화
      shop: {
        mainTitle:     '상점',
        cat_gacha_label: '동료 뽑기',
        cat_gacha_desc:  '골드 또는 다이아로 동료 파편/완전체를 획득합니다.',
        cat_exchange_label: '재화 교환',
        cat_exchange_desc:  '다이아몬드로 각종 재화를 교환합니다.',
        cat_lawExchange_label: '동료 파편 상점',
        cat_lawExchange_desc:  '동료 파편을 규율석(법칙 재화)으로 교환합니다.',
        gachaTitle:      '동료 뽑기',
        exchangeTitle:   '재화 교환',
        lawExchangeTitle:'동료 파편 상점',
        goldGachaTab:    '골드 뽑기',
        diamondGachaTab: '다이아 뽑기',
        pull1:   '1회',
        pull10:  '10+1회',
        pull100: '100+10회',
        goldPoolDesc:    '커먼~에픽 동료 파편 · 완전체 (80% 파편 / 20% 완전체)',
        diamondPoolDesc: '레어~스페셜 동료 파편 · 완전체 (80% 파편 / 20% 완전체)',
        resultsHeader:   '뽑기 결과 ({n}개)',
        fragInventory:   '파편 보유 현황',
        universalFrag:   '만능 파편',
        universalFragDesc: '5개 = 동료 별 1개',
        owned:           '보유중',
        canSummon:       '소환 가능',
        summoned:        '완전체!',
        dupeToFrag:      '(중복→파편×10)',
        frag:            '파편',
        exchangeIntroTpl:  '💎 다이아몬드로 재화를 교환합니다 · 보유 💎 {n}',
        exchangeEach:      '획득',
        lawExchangeLockedTitle: '시즌6 오픈 필요',
        lawExchangeLockedDesc:  '원계(시즌6)가 열리면 이용할 수 있습니다.',
        lawExchangeIntroTpl:    '중복으로 쌓인 동료 파편을 규율석으로 교환합니다 · 보유 {icon}{n}',
        lawHaveRateTpl:         '보유 {have}개 · {rate}개당 {icon}1개',
        exchangeBtn:            '전부 교환',
        item_gold:           '골드',
        item_ganghwaseok:    '강화석',
        item_cheonunseok:    '천운석',
        item_cheonryeonggwa: '천령과',
        item_taegeukseok:    '태극석',
        item_chaewonseok:    '차원석',
        item_hondonseok:     '혼돈석',
        item_sullriseok:     '순리석',
        item_soulStones:     '영혼석',
        item_universalFragments: '만능파편',
      },

      // ── 건물 화면 ──
      building: {
        title:        '건물',
        restoreStatus:'귀-인-국 복원 현황',
        current:      '현재',
        build:        '건설',
        maxLevel:     '✨ 신령화 완성 ✨',
        back:         '← 귀환',
        level_0: '폐허',
        level_1: '복구',
        level_2: '활성화',
        level_3: '축복',
        level_4: '신령화',
        noEffect:     '효과 없음',
        specialEffect:'특수 효과',
        eff_atk:      '공격력',
        eff_hp:       '최대HP',
        eff_xp:       '경험치',
        eff_weapon:   '런 시작 시 무기',
        eff_weaponRare:'(희귀 포함)',
        eff_select:   '개 선택',
        eff_afterRun: '런 종료 후 HP',
        eff_revive:   '부활권 지급',
        eff_autoRevive:'자동 부활',
        eff_compAtk:  '동료 공격력',
        eff_compHp:   '동료 HP',
        eff_petSlot:  '펫 슬롯',
        eff_petMult:  '펫 효과',
        // [UPDATE 2026-08-06] 텍스트 중앙화 (building-scene.js)
        noEffectYet:         '효과 없음',
        costDiscountPrefix:  '강화 비용 -',
        dungeonIncomePrefix: '던전 수익 +',
        noBuildingsUnlocked: '아직 해금된 건물이 없습니다.',
        goBuilding:          '건물 가기',
        maxShort:            '✨ 최대',
        upgradeBtn:          '강화',
        role:                '역할',
        upgradeLevelsHeader: '강화 단계',
        maxCompleteDetail:   '✨ 최대 강화 완료',
      },

      // ── 로비 다이얼로그 ──
      lobbyDialogue: {
        resolve:       '내가... 모두를... 반드시...!',
        firstClear:    '좋아! 이렇게 하나씩 하는거야!',
        unlock_5:      '대장간이 열렸어!',
        unlock_10:     '동료를 구했어!',
        unlock_15:     '미궁이 구했어!',
        unlock_20:     '건물 강화가 가능해!',
        unlock_25:     '동물 동료를 구했어!',
        unlock_30:     '마침내... 드디어.. 모두를!!!!',
      },

      // ── 대장간(blacksmith-scene.js) ── [UPDATE 2026-08-06] 텍스트 중앙화 파일럿 — 기존엔 씬 파일 안에
      // isEn?'...':'...' 삼항식으로 흩어져 있던 문구를 전부 여기로 이관. {n}/{slot}/{label} 등은 코드에서 .replace()로 채움.
      blacksmith: {
        title:              '대장간',
        slotLabel:          '슬롯 {n}',
        empty:               '비어있음',
        active:              '▶선택중',
        elementRelations:    '오행 상생상극 (반전 = 선택한 슬롯)',
        equipped:            '장착중',
        equippedIn:          '{slot}에 장착중',
        equipTo:             '{slot}에 장착',
        default:             '기본 제공',
        enhance:             '강화',
        transcend:           '초월',
        dmgSuffix:           '데미지',
        subMechanicActive:   '서브 메커닉 발동',
        transcendMax:        'MAX',
        transcendLocked:     '초월은 5각 Lv4(★MAX) 도달 시 해금',
        next:                '다음',
        unitSuffix:          '개', // [UPDATE 2026-08-06] "다음: ... 강화석 5개" — 한글 전용 수량 단위(영어는 없음)
        weapons: {
          talisman:    { name: '부적',        desc: '귀신을 봉인하는 부적을 날린다.' },
          sword:       { name: '신검',        desc: '신령한 검으로 적을 베어낸다.' },
          bow:         { name: '신궁',        desc: '정확한 화살로 적을 꿰뚫는다.' },
          staff:       { name: '무당 지팡이', desc: '영혼체가 주변을 선회하며 공격한다.' },
          scythe_main: { name: '영혼낫',      desc: '초승달 낫이 주변을 회전하며 베어낸다.' },
        },
        talismanCard: {
          banner:      '기록이 허락되지 않은 부적',
          title:       '수호 부적',
          desc:        '장착할 수 없다. 오직 대비를 위해 강화할 수만 있다.',
          durability:  '내구 강화',
          power:       '일반강화',
        },
      },

      // ── 엔딩(ending-scene.js) ── [UPDATE 2026-08-06] 텍스트 중앙화 — 시즌별 슬라이드 대사를 여기로 이관.
      // ending-scene.js의 SLIDES* 배열엔 bg/color/duration/img/accent(연출용 메타데이터)만 남기고,
      // 실제 대사는 Lang.get('ending.seasonN.인덱스')로 조회(슬라이드 인덱스 = 배열 순서, 0부터).
      ending: {
        ui: {
          skip: '건너뛰기',
          seasonComplete: '시즌 {n} 완료',
          tapToContinue: '탭하여 계속',
        },
        season1: [
          ["현계의 원혼들이 잠들었다.", "귀인국에 오랜만에 평화가 찾아왔다."],
          ["그러나 혼돈은 더 깊은 곳에서 시작되고 있었다.", "이제 다른 차원을 도울 때다, 애기씨야."]
        ],
        season2: [
          ["멈춰있던 넋들이, 다시 강을 따라 흐르기 시작했다.", "저승나비가 그 위를 조용히 맴돈다."],
          ["타락에서 돌아온 바리공주가 상사화 한 송이를 건넨다.", "\"이 꽃처럼... 나도 누군가를 다시 만날 수 있을까.\""],
          ["그러나 어딘가에서, 실눈 하나가 천천히 떠졌다."],
          ["숲 곳곳에서 낄낄거리는 기척이 느껴진다.", "누군가... 지켜보고 있다."],
          ["먼동이 트고 있었다.", "\"망랑계의 문이... 열리고 있어.\""]
        ],
        season3: [
          ["망랑계의 혼란이 서서히 가라앉았다.", "그런데 도깨비들은... 여전히 웃고 있었다."],
          ["\"애기씨가 이겼다아아!!\"", "박수와 장구애비가 대뜸 뒤풀이를 선포했다."],
          ["꺽쇠는 저 멀리서 그 광경을 가만히 지켜보았다.", "\"...저 녀석한테도, 언젠가는 말해줘야겠지.\""],
          ["흥겨운 등불 사이로, 밤하늘 한쪽이 소리없이 갈라져 있었다.", "\"...귀허계도, 뭔가 이상해.\" 애기씨 홀로, 조용히 그 틈을 바라보았다."]
        ],
        season4: [
          ["오랫동안 갇혀있던 넋들이, 마침내 위로 향하는 길을 되찾았다."],
          ["빛으로 이루어진 계단이 스스로 놓였다.", "순리를 따라, 거듭남을 향해."],
          ["귀허계의 문이 마침내 열렸다.", "그 너머엔... 아직 이름 모를 무언가가 있었다."],
          ["구름과 벚꽃이 흐르는 곳.", "넋들이 편안히 흩어지는 그곳을, 애기씨는 처음 보았다."],
          ["「선계」라 불리는 곳이라 했다. 평화로워 보였다.", "그런데... 왜 이렇게, 발밑이 서늘한 걸까."],
          ["어쩌면... 선계도.", "...... 어쩌면...... 전 차원이......"]
        ],
        season5: [
          ["선계의 문이 다시 열렸다.", "구름 사이로, 아주 오랜만에 맑은 빛이 스며들었다."],
          ["그러나 완전히 낫지는 않았다.", "선계 수호신도, 신선들도... 어딘가 지쳐 보였다."],
          ["\"고맙다, 애기씨야. 하지만... 이건 시작에 불과했던 것 같구나.\"", "수호신이 낮게 읊조렸다."],
          ["선계보다 더 깊은 곳, 원계에서부터.", "오래전에 무언가 이미 새어나오고 있었다."],
          ["애기씨는 조용히 하늘 너머를 바라보았다.", "\"......다음은, 저곳인가.\""]
        ],
        season6: [
          ["원계를 향해 걸음을 옮겼다.", "그러나 닿기도 전, 낯선 회랑이 그녀를 맞았다."],
          ["부서진 법칙의 조각들이 허공에 떠 있었다.", "중력도, 인과도, 윤회도 — 온전한 모습이 아니었다."],
          ["금이 간 거울 속에서, 낯익은 얼굴이 그녀를 마주 보았다.", "\"...... 아니야. 그럴 리 없어.\""],
          ["그녀는 조각들을 그러모아 하나로 품었다.", "완전히 이해하지 못한 채로, 일단 손에 쥐었다."],
          ["법칙의 일부를 얻었다.", "하늘이 갈라진 틈 너머, 어계가 그녀를 기다리고 있었다."]
        ],
        season7: [
          ["기어오는 혼돈에는 의지도, 악의도 없었다.", "그저 멸망으로 기울어가는 우주의 비명이었을 뿐.", "그리고 마침내... 부정하고 싶었던 진실이 넋을 관통한다."],
          ["나는 물질도, 반물질도 아니었다.", "우주가 생겨난 이래... 온전히 나 하나만이, 둘로 나뉘지 않은 채 홀로 존재했다.", "나는, 전 우주를 통틀어 혼자만이 혼자였다."],
          ["하지만 보아라... 내가 짊어진 이 외신의 오염을.", "어계를 뚫기 위해 품어버린 이 미친 축복의 찌꺼기를 안고서...", "저 거울을 깨뜨린다면, 우리는 하나가 되기도 전에 소멸할 것이다."],
          ["\"운(運)이란 하늘이 정한 명(命)을 받아들이는 것이 아니라, 제 발로 차고 나가는 의지란다.\"", "\"황계가 이 오염을 이유로 나를 거부한다면...\"", "\"수천 번, 수만 번 스러지며 내 몸의 모든 오염을 다 깎아낼 때까지 덤벼주마.\""],
          ["하나였던 것은 둘이 된다.", "그러나 둘이 된 것은... 마침내 서로를 찾는다."]
        ],
        season8: [
          ["균열 앞에 선다.", "이 너머에, 또 다른 내가 있다."],
          ["눈을 감았다.", "두렵지 않다면 거짓말이었다."],
          ["— 갓난아기였던 그날, 이미 손에 쥐고 있던 빛.", "명(命)은 태어나기 전부터 정해져 있었다."],
          ["갈라진 틈 너머로, 손을 뻗었다.", "반대편에서도, 같은 손이 뻗어왔다."],
          ["손끝이 닿는 순간, 눈물이 흘렀다.", "낮과 밤이, 물질과 반물질이, 마침내 하나의 자리에 섰다."],
          ["별들이 갈라지고, 은하가 그녀를 향해 쏟아졌다.", "전 우주를 통틀어, 혼자만이 혼자였다."],
          ["기록의 법칙조차, 그녀를 붙잡지 못했다.", "존재했다는 사실 그 자체가, 조용히 지워졌다."],
          ["아무도 그녀를 기억하지 못하는 자리에,", "꽃잎만이 그녀가 서 있던 모양으로 내려앉았다."],
          ["그러나 물건은, 법칙이 아니었다.", "부적 하나가, 손에서 손으로 전해졌다."],
          ["그리고 마침내, 어느 어린 무당의 손에 닿았을 때—", "\"...난 기억해.\""]
        ],
      },

    },

    en: {
      // ── 언어 선택 ──
      langSelect: {
        title: 'Select Language',
        ko: '한국어',
        en: 'English',
      },

      // ── 인트로 슬라이드 ──
      intro: [
        { lines: ['Long ago,', 'there was a kingdom where humans and spirits lived together.'] },
        { lines: ['Gwi-In-Guk (鬼人國)', 'Where divine spirits kept the balance,', 'and the Gwi-In walked alongside the living.'], accent: true },
        { lines: ['But then...', 'An unknown force arrived from beyond the sky.'] },
        { lines: ['The Creeping Chaos.', 'A god that twists the very laws of existence.', 'Gwi-In-Guk fell.'], shake: true },
        // [UPDATE 2026-07-15] 260715_MTOPC.md #6: Samsin Halmoni's prophetic dream, one added line (no spoilers)
        { lines: ['Now, as all lies in ruin,', 'the Grandmother of Fate has awakened the last shaman.', '— She had dreamed of a single moon splitting in two, then merging back into one.'] },
        { lines: ['"Aegissi,"', '"Gather the scattered Gwi-In."', '"Restore the fallen kingdom."'], accent: true },
        { lines: ['To seal the Creeping Chaos,', 'to rebuild Gwi-In-Guk —', 'that is your destiny.'] },
      ],

      // ── 공통 UI ──
      ui: {
        skip:        'SKIP',
        tapToStart:  '✦ Tap to Start ✦',
        settings:    'Settings',
        language:    'Language',
        back:        'Back',
        confirm:     'OK',
        cancel:      'Cancel',
        gold:        'Gold',
        gem:         'Gem',
      },

      // ── 네비 ──
      nav: {
        stage:       'Stage',
        daejanggan:  'Blacksmith',
        companion:   'Clinic',
        weapon:      'Shrine',
        building:    'Totem Hall',
        pet:         'Pet',
        petTooltip:  'Dragon Pond',
        player:      'Character',
        sinmok:      'Sacred Tree',
      },
      onboarding: { // [UPDATE 2026-07-09]
        tapStage: 'Tap here!',
        tapStage1: 'Try Stage 1!',
        zoomHint: 'You can pinch to zoom too', // [UPDATE 2026-07-13] 260713_MTOPC.md #20
        atkUpgradeHint: 'You can upgrade your ATK now!', // [UPDATE 2026-07-15] Onboarding right after Stage 1 clear
      },
      currency: {
        gold:           'Gold',
        gems:           'Diamonds',
        ganghwaseok:    'Enhancement Stone',
        cheonunseok:    'Heavenly Stone',
        cheonryeonggwa: 'Spirit Fruit',
        taegeukseok:    'Taeguk Stone',
        chaewonseok:    'Dimensional Stone',
        hondonseok:     'Chaos Stone', // [UPDATE 2026-07-15] 260715_MTOPC.md #4/#9
        sullriseok:     'Sunri Stone',
      },
      dungeon: {
        ganghwaseok:    'Enhancement Dungeon',
        infinite:       'Infinite Dungeon',
        bossrush:       'Boss Rush',
        cheonunseok:    'Heavenly Stone Dungeon',
        cheonryeonggwa: 'Spirit Fruit Dungeon',
        taegeukseok:    'Taeguk Stone Dungeon',
        hondonseok:     'Chaos Stone Dungeon', // [UPDATE 2026-07-15] 260715_MTOPC.md #4/#9
        sullriseok:     'Sunri Stone Dungeon',
        title:          'Dungeon',
        infiniteTitle:  'Endless Mode',
        infiniteDesc:   'Survive endless waves',
        infiniteDetail: '⏱️ No time limit · 🪙 2× Gold drop',
        infiniteDetail2:'Enemies grow stronger each wave. How long can you last?',
        bestRecord:     'Best',
        noRecord:       'None',
        enter:          'Enter →',
        bossRushTitle:  'Boss Rush',
        bossRushDesc:   'Face all bosses back-to-back',
        bossRushDetail: '💎 Earn Diamonds per boss defeated',
        bossRushDetail2:'10 bosses await. Fall once, and it\'s over.',
        bossRecord:     'bosses',
        totalGem:       'Total',
        hint:           'Dungeons can be challenged anytime, separate from Stages',
        back:           '← Back',
        minSec:         'm',
        sec:            's',
        recordTimeTpl:  '{m}m {s}s',
        // [UPDATE 2026-08-06] 텍스트 중앙화 (dungeon-scene.js)
        noRecordText:        'No record',
        bestLabel:           'Best:',
        enterPlain:          'Enter',
        noDungeonsUnlocked:  'No dungeons unlocked yet.\nClear Stage 5 to unlock.',
        upgradeTitle:        'Dungeon Enhancement',
        power:               'Power',
        ratingSafe:          'Safe',
        ratingRisky:         'Risky',
        ratingDanger:        'Very Risky',
        startFromKillTpl:    'Infinite Dungeon runs start from kill {n} (monsters scale accordingly).',
        downgradeRefundTpl:  'Lv down refunds {gold} Gold + {stone} Sky Stone',
        desc_ganghwaseok:    'Enhancement stones drop instead of gold.',
        desc_infinite:       'Endless gold farming dungeon.',
        desc_bossrush:       'Challenge 10 bosses for diamonds.',
        desc_cheonunseok:    'Heavenly stones drop instead of gold.',
        desc_cheonryeonggwa: 'Spirit fruits drop instead of gold.',
        desc_taegeukseok:    'Taeguk stones drop instead of gold.',
        desc_hondonseok:     'Chaos stones drop instead of gold.',
        desc_sullriseok:     'Sunri stones drop instead of gold.',
      },

      // ── 로비 ──
      lobby: {
        enterBuilding:     '▲ Enter',
        locked:            '🔒',
        slotUnlockedTitle: 'Slot Unlocked!',
        slotExpandedMsg:   'expanded to {n}!',
        slotExpandedBody:  'Weapon · Ally · Pet slots',
        slotConfirm:       'OK!',
        diffEasy:          'Easy',
        diffNormal:        'Normal',
        diffHard:          'Hard',
      },

      // ── 업적 ──
      achievement: {
        title:          '🏆 Achievements',
        onceSect:       '◆ One-time',
        infiniteSect:   '◆ Repeating Milestones',
        claim:          'Claim',
        claimed:        'Claimed',
        claimAll:       'Claim All',
        current:        'Current',
        tier:           'Tier',
        first_win_name:         'First Victory',
        first_win_desc:         'Cleared a stage for the first time',
        first_lose_name:        'First Defeat',
        first_lose_desc:        'Fell in battle for the first time',
        first_boss_name:        'First Boss Kill',
        first_boss_desc:        'Defeated a boss for the first time',
        first_companion_name:   'First Companion',
        first_companion_desc:   'Deployed an ally for the first time',
        first_pet_name:         'First Pet',
        first_pet_desc:         'Obtained a pet for the first time',
        first_building_name:    'First Upgrade',
        first_building_desc:    'Upgraded a building for the first time',
        first_evolve_name:      'First Awakening',
        first_evolve_desc:      'Awakened a weapon for the first time',
        all_chapters_name:      'All Chapters',
        all_chapters_desc:      'Cleared all chapters',
        total_kills_name:       'Total Kills',
        total_wins_name:        'Total Clears',
        total_runs_name:        'Total Runs',
        total_kills_inf_name:   'Endless Hunt',
        boss_chapters_inf_name: 'Boss Hunter',
        total_wins_inf_name:    'Winning Streak',
        total_runs_inf_name:    'Unstoppable',
        season1_full_name:      'Hyeongye Complete',
        season1_full_desc:      'Cleared Season 1 (Mortal Realm)',
        season2_full_name:      'Yumyeonggye Complete',
        season2_full_desc:      'Cleared Season 2 (Underworld)',
        season3_full_name:      'Mangranggye Complete',
        season3_full_desc:      'Cleared Season 3 (Realm of Glitches)',
        season4_full_name:      'Gwiheogye Complete',
        season4_full_desc:      'Cleared Season 4 (Realm of the Void)',
        season5_full_name:      'Seongye Complete',
        season5_full_desc:      'Cleared Season 5 (Celestial Realm)',
        hard_clear_name:        'First Hard Clear',
        hard_clear_desc:        'Cleared a stage on Hard difficulty for the first time',
        companion_5_name:       'Companion Collector I',
        companion_5_desc:       'Owned 5 companions',
        companion_10_name:      'Companion Collector II',
        companion_10_desc:      'Owned 10 companions',
        companion_15_name:      'Companion Collector III',
        companion_15_desc:      'Owned 15 companions',
        pet_5_name:              'Pet Collector I',
        pet_5_desc:              'Owned 5 pets',
        pet_10_name:             'Pet Collector II',
        pet_10_desc:             'Owned 10 pets',
        pet_15_name:             'Pet Collector III',
        pet_15_desc:             'Owned 15 pets',
        companion_4star_name:    'Rising Star',
        companion_4star_desc:    'Upgraded a companion to 4 stars',
        companion_awakened_name: 'Companion Awakened',
        companion_awakened_desc: 'Awakened a companion',
        seonsul_unlock_name:     'Seonsul Initiate',
        seonsul_unlock_desc:     'Learned the Seonsul skill tree for the first time',
        seonsul_dual_tree_name:  'Yin-Yang Harmony',
        seonsul_dual_tree_desc:  'Grew a second Seonsul tree',
        building_lv5_name:       'Thriving Village',
        building_lv5_desc:       'Upgraded a building to level 5',
        gold_10k_name:           'Wealth Accumulated',
        gold_10k_desc:           'Held 10,000 gold',
        gem_50_name:             'Gem Stash',
        gem_50_desc:             'Held 50 gems',
        kills_50000_name:        'Exterminator',
        kills_50000_desc:        'Reached 50,000 total kills',
      },

      // ── 스테이지 ──
      chapters: [
        'The Forgotten Grave',
        'Village of Mist',
        'The Corrupted Shrine',
        'Forest of Spirits',
        'The Rift of Chaos',
        'Gates of the Underworld',
        'Tower of the Void',
        'Sea of Oblivion',
        'Realm of the Outer God',
        'Heart of Gwi-In-Guk',
      ],

      // ── 설정 메뉴 ──
      settingsMenu: {
        title:    'Settings',
        language: 'Language',
        sound:    'Sound FX',
        bgm:      'Music',
        version:  'Version',
        tutorial: 'Help',
        redeemCode: 'Redeem Code', // [UPDATE 2026-07-15] 260715_MTOPC.md #2
        redeemCodePlaceholder: 'Enter code',
        redeemCodeSubmit: 'Confirm',
        // [UPDATE 2026-07-17] Save Code (for moving progress between PC/mobile — itch.io doesn't auto-sync saves)
        saveCode: '💾 Save Code',
        saveCodeExport: 'Export',
        saveCodeImport: 'Import',
        saveCodeExportTitle: 'Export Save Code',
        saveCodeExportDesc: 'Copy the code below and keep it somewhere safe. Paste it into "Import" on another device to carry your progress over.',
        saveCodeCopyBtn: '📋 Copy',
        saveCodeCopied: 'Copied!',
        saveCodeCopyManual: 'Copy button isn\'t supported here. Long-press the code below to select and copy it manually.',
        saveCodeImportTitle: 'Import Save Code',
        saveCodeImportPlaceholder: 'Paste your save code here',
        saveCodeImportSubmit: 'Confirm',
        saveCodeInvalid: 'Invalid code.',
        saveCodeChecksumError: 'The code looks corrupted or truncated. Please check you copied the entire thing.',
        saveCodePreviewTitle: 'Apply this save?',
        saveCodePreviewVersion: 'Version',
        saveCodePreviewStage: 'Highest Stage',
        saveCodePreviewAchievements: 'Achievements',
        saveCodePreviewBuildings: 'Buildings',
        saveCodePreviewCompanions: 'Companions',
        saveCodePreviewPets: 'Pets',
        saveCodePreviewCurrency: 'Currency',
        saveCodePreviewSavedAt: 'Saved At',
        saveCodePreviewDevice: 'Saved On',
        saveCodeApply: 'Apply',
        // [UPDATE 2026-07-31] Automatic backup made "cannot be undone" untrue — reworded
        saveCodeApplyWarn: '⚠️ This will overwrite your current progress.\nYour current save is backed up first, and can be restored once from Settings.',
        saveCodeCancel: 'Cancel',
        saveCodeApplied: 'Applied! Returning to the lobby...',
        // [UPDATE 2026-07-31] Restore — roll back to the save automatically kept before an import overwrote it
        saveCodeRestore: '↩️ Restore',
        saveCodeRestoreTitle: 'Restore Previous Save',
        saveCodeRestoreDesc: 'Rolls back to the save that was automatically kept just before you imported a save code.',
        saveCodeRestoreWarn: '⚠️ Your current progress will be lost.\nThe backup is single-use, so this cannot be undone again.',
        saveCodeRestoreConfirm: 'Restore',
        saveCodeRestoreDone: 'Restored! Returning to the lobby...',
        saveCodeRestoreFail: 'There is no backup to restore.',
        devicePC: 'PC',
        deviceMobile: 'Mobile',
        // [UPDATE 2026-07-16] Settings - Reboot (full reset) button
        reboot: '🔄 Re-boot',
        rebootWarn1: 'Warning: There is no reward whatsoever. This button only lets you start the game over from scratch.\nDo you want to continue?',
        rebootWarn2: 'Warning: Truly no reward for starting over. No hidden content either.',
        rebootWarn3: 'Warning: This is your final warning. This serves no purpose other than restarting the game from the beginning.',
        rebootYes: 'Yes',
        rebootNo: 'No',
        rebootDone: 'The game will restart from the beginning.',
        rebootBonus: '🎉 Hidden Achievement Unlocked: The Resolve to Restart — +5000 Gems! (one-time)',
        rebootConfirmClose: 'OK',
      },

      // ── Tutorial ──
      tutorial: {
        title:   'How to Play',
        skip:    'Skip',
        prev:    'Back',
        next:    'Next',
        close:   "Let's Go!",
        slide1_title: '🎮 Movement & Combat',
        slide1_body:  'Mobile: Use the joystick on the left side\nPC: Arrow keys or WASD\n\nAegissi attacks the nearest enemy automatically.\nSurvive and exorcise all the spirits!',
        slide2_title: '⚔️ Weapons & Level Up',
        slide2_body:  'Defeating enemies grants experience points.\nOn level up, choose or upgrade a weapon.\n\nUpgrading a weapon 3 times makes it evolve into a more powerful form!',
        slide3_title: '👥 Allies & Pets',
        slide3_body:  'Form a party with allies and pets from the lobby.\n\nAllies: fight alongside you — attacking, defending, healing\nPets: grant passive stat boosts or trigger special abilities',
        slide4_title: '🏛️ Building Upgrades',
        slide4_body:  'Click any building in the lobby to upgrade it with gold.\n\nUpgrades permanently increase stats like\nHP, attack power, and gold earnings!',
      },

      // ── 동료 화면 ──
      character: {
        title:       'Allies',
        formation:   'Party',
        emptySlot:   'Empty',
        owned:       'Allies',
        active:      'Active',
        back:        '← Back',
        deploy:           'Deploy',
        shopBtn:          '🎪 Companion Shop (Gacha) →',
        elementRelations: 'Element Relations (colored = deployed)', // [UPDATE 2026-08-06] 텍스트 중앙화
        nextAwakening:    'Next',
        fragCount:        'Shards',
        canSummon:        'Summon ready!',
        summonBtn:        '🎴 Summon (10 Shards)',
        uniFragBtn:       '✨ All-Frag ×5 → Star Up',
        awoken:           'Awoken',
        slotUnlockNormal: 'Normal Unlock',
        slotUnlockHard:   'Hard Unlock',
        rarity_common:    'Common',
        rarity_uncommon:  'Uncommon',
        rarity_rare:      'Rare',
        rarity_unique:    'Unique',
        rarity_epic:      'Epic',
        rarity_legendary: 'Legendary',
        rarity_mythos:    'Mythos',
        rarity_special:   '★Special',
        rarity_universal: 'Universal', // [UPDATE 2026-08-06] 텍스트 중앙화(shop-scene.js)
        role_tank:      'Tank',
        role_dps:       'DPS',
        role_healer:    'Healer',
        role_support:   'Support',
        role_assassin:  'Assassin',
      },

      // ── 캐릭터(플레이어) 화면 ──
      player: {
        title:         'Character',
        charName:      'Aegissi',
        charSubtitle:  'The Last Shaman',
        upgradeHint:   'Permanently upgradeable with Gold in the Lobby',
        mainWeapon:    'Main Weapon',
        weaponLocked:  '🔒 Clear Stage 10 to change your main weapon.',
        equipped:      'Equipped',
        statSection:   'Stats & Upgrades',
        upgradeBtn:    'Upgrade',
        upgraded:      'upgraded',
        upgradeHintFooter: 'Stats auto-increase on level-up · Reset after each run',
        upgradeFooter2:    'Gold upgrades are permanent',
        back:          '← Back',
        stat_atk: { label:'ATK',    desc:'Increases weapon damage' },
        stat_spd: { label:'SPD',    desc:'Reduces weapon cooldown' },
        stat_mov: { label:'MOV',    desc:'Player movement speed' },
        stat_def: { label:'DEF',    desc:'Reduces damage taken' },
        stat_eva: { label:'EVA',    desc:'Chance to evade damage (max 40%)' },
        stat_hp:  { label:'HP',     desc:'Increases max HP' }, // [UPDATE 2026-07-16] 260716_MTOPC.md #3
        slotLabel:     'Weapon Slot',
        slotDeselect:  '(click to deselect)',
      },

      // ── 신목 강화 ──
      sinmok: {
        title:           '🌳 Sacred Tree Upgrades',
        locked:          '(Unlock: Clear Stage 30)',
        current:         'Current',
        stat_critChance: 'Crit Chance',
        stat_critMult:   'Crit Mult',
        stat_atkSpd:     'Atk Speed',
        stat_movSpd:     'Mov Speed',
        stat_evasion:    'Evasion',
      },

      // ── 펫 화면 ──
      pet: {
        title:       'Pets',
        formation:   'Party',
        emptySlot:   'Empty',
        activeEffect:'Active Effects',
        owned:       'Pets',
        active:      'Active',
        back:        '← Back',
        // [UPDATE 2026-08-06] 텍스트 중앙화
        maxLabel:    'MAX',
        lvLabel:     'Lv.{n}',
        unlock:      'Unlock',
        deploy:      'Deploy',
        upgrade:     'Upgrade',
        clearChapterToUnlock: 'Clear Chapter {n}',
        unlockSeasonRequired: 'Unlock Season {n}',
      },

      // [UPDATE 2026-07-19] Vault — season specialty items (Hard-mode-only drops)
      vault: {
        title:       'Vault',
        tabSpecialty:'Specialty',
        tabLaw:      'Law Artifact',
        lawLocked:   'This section is not open yet.',
        hardOnly:    'Hard difficulty stages only',
        owned:       'Owned',
        back:        '← Back',
        // [UPDATE 2026-08-06] 텍스트 중앙화
        kindPlain:       'Plain',
        kindConditional: 'Conditional',
        subTabPassive:   'Passive (auto — no slot needed)',
        subTabActive:    'Active (equip 3 slots)',
        emptySlot:       'Empty',
        passive:         'Passive',
        active:          'Active',
        appliedBadge:    '✓ Active',
        maxLabel:        'MAX',
        locked:          'Locked',
        unlock:          'Unlock',
        enhance:         'Enhance',
        equip:           'Equip',
        equippedBadge:   '✓ Equipped',
        have:            'Have {icon}{n}',
      },

      // ── 상점(shop-scene.js) ──
      shop: {
        mainTitle:     'Shop',
        cat_gacha_label: 'Companion Gacha',
        cat_gacha_desc:  'Spend Gold or Diamonds to get companion fragments and summons.',
        cat_exchange_label: 'Currency Exchange',
        cat_exchange_desc:  'Exchange Diamonds for various resources.',
        cat_lawExchange_label: 'Fragment → Rule Stone',
        cat_lawExchange_desc:  'Exchange companion fragments for Rule Stones (used for Laws).',
        gachaTitle:      'Companion Gacha',
        exchangeTitle:   'Currency Exchange',
        lawExchangeTitle:'Fragment Exchange',
        goldGachaTab:    'Gold Gacha',
        diamondGachaTab: 'Diamond Gacha',
        pull1:   '×1',
        pull10:  '×10+1',
        pull100: '×100+10',
        goldPoolDesc:    'Common~Epic companion fragments & summons (80% frag / 20% full)',
        diamondPoolDesc: 'Rare~Special companion fragments & summons (80% frag / 20% full)',
        resultsHeader:   'Results ({n})',
        fragInventory:   'Fragment Inventory',
        universalFrag:   'Universal Fragment',
        universalFragDesc: '5 = 1 Companion Star',
        owned:           'Owned',
        canSummon:       'Can Summon',
        summoned:        'Summoned!',
        dupeToFrag:      '(Dupe→Frag×10)',
        frag:            'Frag',
        exchangeIntroTpl:  '💎 Exchange Diamonds for resources · Have 💎 {n}',
        exchangeEach:      'each',
        lawExchangeLockedTitle: 'Requires Season 6',
        lawExchangeLockedDesc:  'This shop unlocks once the Primal Realm arrives.',
        lawExchangeIntroTpl:    'Exchange duplicate companion fragments for Rule Stones · Have {icon}{n}',
        lawHaveRateTpl:         'Have {have} · {rate} → {icon}1',
        exchangeBtn:            'Exchange',
        item_gold:           'Gold',
        item_ganghwaseok:    'Enhance Stone',
        item_cheonunseok:    'Sky Stone',
        item_cheonryeonggwa: 'Spirit Fruit',
        item_taegeukseok:    'Taeguk Stone',
        item_chaewonseok:    'Dimension Stone',
        item_hondonseok:     'Chaos Stone',
        item_sullriseok:     'Sunri Stone',
        item_soulStones:     'Soul Stone',
        item_universalFragments: 'Universal Fragment',
      },

      // ── 건물 화면 ──
      building: {
        title:        'Buildings',
        restoreStatus:'Gwi-In-Guk Restoration',
        current:      'Current',
        build:        'Build',
        maxLevel:     '✨ Fully Restored ✨',
        back:         '← Back',
        level_0: 'Ruins',
        level_1: 'Repaired',
        level_2: 'Active',
        level_3: 'Blessed',
        level_4: 'Divine',
        noEffect:     'No Effect',
        specialEffect:'Special Effect',
        eff_atk:      'ATK',
        eff_hp:       'Max HP',
        eff_xp:       'EXP',
        eff_weapon:   'Start run with',
        eff_weaponRare:'(incl. rare)',
        eff_select:   'weapon(s)',
        eff_afterRun: 'HP after run',
        eff_revive:   'Revive token',
        eff_autoRevive:'Auto-revive',
        eff_compAtk:  'Ally ATK',
        eff_compHp:   'Ally HP',
        eff_petSlot:  'Pet slots',
        eff_petMult:  'Pet effects',
        // [UPDATE 2026-08-06] 텍스트 중앙화 (building-scene.js)
        noEffectYet:         'No effect yet',
        costDiscountPrefix:  'Upgrade cost -',
        dungeonIncomePrefix: 'Dungeon income +',
        noBuildingsUnlocked: 'No buildings unlocked yet.',
        goBuilding:          'Enter',
        maxShort:            '✨ MAX',
        upgradeBtn:          'Upgrade',
        role:                'Role',
        upgradeLevelsHeader: 'UPGRADE LEVELS',
        maxCompleteDetail:   '✨ Max Level',
      },

      // ── 로비 다이얼로그 ──
      lobbyDialogue: {
        resolve:       "I'll protect them... every last one...!",
        firstClear:    'Yes! One down, many to go!',
        unlock_5:      'The Forge is open!',
        unlock_10:     'A companion joins me!',
        unlock_15:     'The Dungeon unlocked!',
        unlock_20:     'Village upgrades available!',
        unlock_25:     'A creature joins my side!',
        unlock_30:     'At last... I saved them all!!!!',
      },

      // ── 대장간(blacksmith-scene.js) ── [UPDATE 2026-08-06] 텍스트 중앙화 파일럿
      blacksmith: {
        title:              'Blacksmith',
        slotLabel:          'Slot {n}',
        empty:               'Empty',
        active:              '▶Active',
        elementRelations:    'Element Relations (highlighted = current slot)',
        equipped:            'Equipped',
        equippedIn:          'In {slot}',
        equipTo:             'Equip: {slot}',
        default:             'Default',
        enhance:             'Enhance',
        transcend:           'Transcend',
        dmgSuffix:           ' dmg',
        subMechanicActive:   'Sub-mechanic active',
        transcendMax:        'MAX',
        transcendLocked:     'Transcend unlocks at ★MAX (5-awaken Lv4)',
        next:                'Next',
        unitSuffix:          '',
        weapons: {
          talisman:    { name: 'Talisman', desc: 'Launches a sealing talisman.' },
          sword:       { name: 'Sword',    desc: 'Slash enemies with a divine sword.' },
          bow:         { name: 'Bow',      desc: 'Pierce enemies with precise arrows.' },
          staff:       { name: 'Staff',    desc: 'Spirit orbs orbit and strike foes.' },
          scythe_main: { name: 'Scythe',   desc: 'A crescent scythe rotates and slashes.' },
        },
        talismanCard: {
          banner:      'A talisman the Record does not permit',
          title:       'Guardian Talisman',
          desc:        'Cannot be equipped. Only strengthened, in preparation.',
          durability:  'Durability',
          power:       'Power',
        },
      },

      // ── 엔딩(ending-scene.js) ── [UPDATE 2026-08-06] 텍스트 중앙화
      ending: {
        ui: {
          skip: 'Skip',
          seasonComplete: 'Season {n} Complete',
          tapToContinue: 'Tap to continue',
        },
        season1: [
          ["The restless spirits of the Living World are at rest.", "Peace has returned to Gwi-In-Guk at last."],
          ["But chaos was stirring in realms far deeper.", "It is time to help the other dimensions, Aegissi."]
        ],
        season2: [
          ["The souls that had been frozen began to flow along the river once more.", "The Jeoseung Butterfly quietly circles above them."],
          ["Princess Bari, returned from corruption, offers a single sangsahwa flower.", "\"Like this flower... could I meet someone again too?\""],
          ["But somewhere, a single slitted eye slowly opened."],
          ["Snickering presences stir throughout the forest.", "Someone... is watching."],
          ["Dawn was breaking.", "\"The gate to the Chaos Realm... is opening.\""]
        ],
        season3: [
          ["The chaos of the Illusion Realm slowly settled.", "And yet the dokkaebi... were still laughing."],
          ["\"Aegissi won! Aegissi WON!!\"", "Baksu and Janggu-aebi immediately declared an after-party."],
          ["Ggeoksoe watched the scene quietly from afar.", "\"...I suppose I'll have to tell him, someday.\""],
          ["Amid the festive lanterns, a silent crack split the night sky.", "\"...Something's off, in the Void Realm too.\" Alone, Aegissi quietly gazed at the rift."]
        ],
        season4: [
          ["The spirits long trapped at last found their way upward once more."],
          ["A staircase of light laid itself out.", "Following the natural order, toward rebirth."],
          ["The gate of the Void Realm finally opened.", "And beyond it... something as yet unnamed awaited."],
          ["A place where clouds and cherry blossoms drifted.", "Aegissi saw it for the first time — where souls could finally rest."],
          ["They called it the Celestial Realm. It looked peaceful.", "And yet... why did the ground beneath her feel so cold?"],
          ["Maybe... even the Celestial Realm.", "...... Maybe...... every single realm......"]
        ],
        season5: [
          ["The gate of the Celestial Realm opened once more.", "For the first time in ages, clear light filtered through the clouds."],
          ["But it was not fully healed.", "The guardian god, the immortals... all seemed weary, somehow."],
          ["\"Thank you, Aegissi. But... I fear this was only the beginning.\"", "The guardian god murmured, low and quiet."],
          ["From somewhere deeper than the Celestial Realm — the Primal Realm.", "Something had already begun to seep out, long ago."],
          ["Aegissi quietly gazed beyond the sky.", "\"...... So that's where I'm needed next.\""]
        ],
        season6: [
          ["She walked toward the Primal Realm.", "But before she could arrive, an unfamiliar corridor received her instead."],
          ["Shattered fragments of law hung suspended in the air.", "Gravity, causality, reincarnation — none of them whole."],
          ["From within the cracked mirror, a familiar face looked back.", "\"...... No. That can't be true.\""],
          ["She gathered the fragments and held them close.", "Without fully understanding, she took hold of them anyway."],
          ["She had obtained a piece of Law.", "Beyond the tear in the sky, the Barren Realm awaited her."]
        ],
        season7: [
          ["The crawling chaos held neither will nor malice.", "It was only the scream of a universe tilting toward ruin.", "And at last... the truth she had wanted to deny pierced her soul."],
          ["I was neither matter nor antimatter.", "Since the universe began... I alone existed whole, never split in two.", "In all the cosmos, I was the only one who was alone."],
          ["But look... at this Outer God's corruption I carry.", "Holding the dregs of that mad blessing I swallowed to breach the Barren Realm...", "If I shatter that mirror now, we will perish before we ever become one."],
          ["\"Fortune is not accepting the fate the heavens assign — it is the will to kick your way out of it.\"", "\"If the Ruined Realm turns me away over this corruption...\"", "\"Then I will fall a thousand times, ten thousand times, and keep coming until every last stain is scraped from me.\""],
          ["What was one becomes two.", "But what has become two... will, at last, find each other."]
        ],
        season8: [
          ["She stood before the rift.", "Beyond it waited another her."],
          ["She closed her eyes.", "It would be a lie to say she wasn’t afraid."],
          ["— Even as a newborn, a light already in her hands.", "Her fate had been set before she was born."],
          ["She reached across the divide.", "And from the other side, the same hand reached back."],
          ["The instant their fingers touched, tears fell.", "Day and night, matter and antimatter, stood at last in the same place."],
          ["The stars split open, and galaxies poured toward her.", "In all the cosmos, she alone had been alone."],
          ["Even the Law that records all things could not hold her.", "The very fact that she had existed was quietly erased."],
          ["In the place no one remembered her standing,", "only fallen petals kept the shape where she once stood."],
          ["But an object was not a Law.", "A single talisman passed from hand to hand."],
          ["And at last, when it reached the hands of a young shaman—", "\"...I remember.\""]
        ],
      },

    },
  };

  function set(lang) {
    if (TEXT[lang]) {
      current = lang;
      Save.setLang(lang);
    }
  }

  function get(path) {
    // 'intro.0.lines' 같은 점 표기법 지원
    const keys = path.split('.');
    let val = TEXT[current];
    for (const k of keys) {
      if (val === undefined) return path;
      val = isNaN(k) ? val[k] : val[parseInt(k)];
    }
    return val ?? path;
  }

  // 단축 접근
  function t(section, key) {
    return TEXT[current]?.[section]?.[key] ?? key;
  }

  function init() {
    current = Save.getLang() || 'ko';
  }

  function getCurrent() { return current; }
  function getSlides()  { return TEXT[current].intro; }

  return { set, get, t, init, getCurrent, getSlides };
})();
